providers:
  - CUDAExecutionProvider
  - CPUExecutionProvider

models:
  ckpts_dir: ./checkpoints
  insightface:
    home: ./checkpoints
    link: https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip
  face_detection_model:
    name: retinaface_resnet50
    path: ./checkpoints/detection_Resnet50_Final.pth
    link: https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth
  face_swap_model:
    name: inswapper_128
    path: ./checkpoints/inswapper_128.onnx
    link: https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx
  face_restoration_model:
    name: codeformer
    path: ./checkpoints/codeformer-v0.1.0.pth
    link: https://huggingface.co/datasets/Gourieff/ReActor/resolve/main/models/facerestore_models/codeformer-v0.1.0.pth
  face_parse_model:
    name: parsenet
    path: ./checkpoints/parsing_parsenet.pth
    link: https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth

params:
  face_restore_visibility: 1.0
  codeformer_weight: 0.5